// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://zlkefvmjdlqewcreqhko.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Inpsa2Vmdm1qZGxxZXdjcmVxaGtvIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDk5MTI2ODcsImV4cCI6MjA2NTQ4ODY4N30.MJe_4Gvtpj2x1J5TcLorVXzyNFrMxjLvh0mBLXdhNT8";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);